In [20]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [26]:
data=['cat','dog','cow','camel']
#data1=['apple','apple','orange','apple','banana','banana','orange','apple']


In [27]:
le=LabelEncoder()
integer_encoded = le.fit_transform(data)
print(integer_encoded)

[1 3 2 0]


In [28]:
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded= onehot_encoder.fit_transform(integer_encoded)

print(integer_encoded)
print(onehot_encoded)

[[1]
 [3]
 [2]
 [0]]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
